# Generated by Django 2.1.7 on 2020-10-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0014_problem_share_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='submission_test_case_info',
            field=models.BooleanField(default=True),
        ),
    ]
